package main

import (
	"context"
	"encoding/json"
	"strings"

	"charm.land/fantasy"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// agent_tools_bridge.go gives the in-process agent sessions native
// twins of the linear_* bridge tools so they no longer attach the HTTP
// bridge at all. The bridge handlers and these natives share the same
// cwd-parameterized core functions in mcp_linear.go, so behavior —
// gating, errors, output shapes — is identical on both paths. These
// tools live in the deferred tool registry (agent_tools_registry.go):
// they are never part of the wire tool definitions and are reached
// through search_tools + invoke_tool.
//
// The 8 ask-built-in workflow_* tools (and clear_plans) used to live
// here too but were promoted to the core wire toolset — see
// agent_tools_workflow.go. The promotion is a deliberate, documented
// core exception (the two-stage workflow guard forces the model to
// call workflow_list and workflow_run as a precondition for multi-step
// work; an extra search_tools round-trip per guard interaction was
// pure overhead). nativeBridgeTool, bridgeAgentTool, and
// mcpResultText are still reused by agent_tools_workflow.go.

// nativeBridgeTool adapts one bridge core to fantasy's AgentTool. The
// input schema is generated by the same jsonschema machinery the MCP
// SDK uses, so the `jsonschema:"..."` field docs the bridge tools were
// written with reach the model unchanged. The returned text is the
// handler's summary line plus the structured output JSON (when the
// two differ), mirroring what an MCP client sees as text + structured
// content.
//
// jsonschema-go emits nullable fields as `type: ["null", X]` for both
// `*T` pointers and `omitempty` slices — its JSON-Schema 2020-12
// dialect. The OpenAI tool format (and the strict Moonshot / OpenAI
// schema validators) treats optional tool inputs as absent-or-present,
// never JSON null, and they reject schemas that mix null with another
// type. Compounding the issue, fantasy's downstream `schema.Normalize`
// rewrites those type-arrays into `anyOf` whose array branch carries
// its own `items: {}` while the parent keeps its real `items` —
// "conflicting keywords found in anyOf with parent", the error this
// adapter used to surface to the model on every workflow_create /
// workflow_edit call.
//
// `flattenNullableTypes` walks the schema and drops `"null"` from any
// `type` array, reducing `["null", "array"]` to `"array"` and
// `["null", "string"]` to `"string"`. Optionality is already expressed
// by the field's absence from `required` (jsonschema-go's omitempty
// mapping), so the runtime contract is unchanged: a missing field
// decodes to the Go zero value, a present field decodes to its value.
// The fantasy Normalize pass then has nothing to rewrite, and the wire
// schema is accepted by every strict validator we ship to.
func nativeBridgeTool[In, Out any](name, description string,
	run func(ctx context.Context, in In) (*mcp.CallToolResult, Out, error),
) fantasy.AgentTool {
	properties := map[string]any{}
	var required []string
	if schema, err := jsonschema.For[In](nil); err == nil {
		if raw, err := json.Marshal(schema); err == nil {
			var m map[string]any
			if json.Unmarshal(raw, &m) == nil {
				if props, ok := m["properties"].(map[string]any); ok {
					properties = props
				}
				if reqs, ok := m["required"].([]any); ok {
					for _, r := range reqs {
						if s, ok := r.(string); ok {
							required = append(required, s)
						}
					}
				}
			}
		}
	} else {
		debugLog("bridge tool %s: schema: %v", name, err)
	}
	flattenNullableTypes(properties)
	// Every native tool carries the user-facing phrase param so the
	// transcript line reads "what is this call doing" instead of raw
	// params. Tools whose input already defines "description" as real
	// payload (linear_create_issue / linear_update_issue use it for
	// the issue's Markdown body) are left untouched.
	if _, exists := properties["description"]; !exists {
		properties["description"] = map[string]any{
			"type":        "string",
			"description": toolPhraseFieldDoc,
		}
		required = append(required, "description")
	}
	return &bridgeAgentTool[In, Out]{
		name:        name,
		description: description,
		properties:  properties,
		required:    required,
		run:         run,
	}
}

// flattenNullableTypes walks a JSON-Schema-shaped map and rewrites any
// `type: [..., "null", ...]` array into a single non-null type
// (string, array, object, …). A type array containing only "null"
// drops the `type` key entirely; an array with multiple non-null
// members is collapsed back to a JSON array (unreachable for our
// generated schemas today, kept defensive). See nativeBridgeTool's
// doc comment for why this exists.
func flattenNullableTypes(v any) {
	switch n := v.(type) {
	case map[string]any:
		if t, ok := n["type"].([]any); ok {
			nonNull := make([]any, 0, len(t))
			for _, x := range t {
				if s, ok := x.(string); !ok || s != "null" {
					nonNull = append(nonNull, x)
				}
			}
			switch len(nonNull) {
			case 0:
				delete(n, "type")
			case 1:
				n["type"] = nonNull[0]
			default:
				n["type"] = nonNull
			}
		}
		for _, child := range n {
			flattenNullableTypes(child)
		}
	case []any:
		for _, item := range n {
			flattenNullableTypes(item)
		}
	}
}

type bridgeAgentTool[In, Out any] struct {
	name        string
	description string
	properties  map[string]any
	required    []string
	run         func(ctx context.Context, in In) (*mcp.CallToolResult, Out, error)
	opts        fantasy.ProviderOptions
}

func (t *bridgeAgentTool[In, Out]) Info() fantasy.ToolInfo {
	required := t.required
	if required == nil {
		required = []string{}
	}
	return fantasy.ToolInfo{
		Name:        t.name,
		Description: t.description,
		Parameters:  t.properties,
		Required:    required,
	}
}

func (t *bridgeAgentTool[In, Out]) Run(ctx context.Context, call fantasy.ToolCall) (fantasy.ToolResponse, error) {
	var in In
	if strings.TrimSpace(call.Input) != "" {
		if err := json.Unmarshal([]byte(call.Input), &in); err != nil {
			return fantasy.NewTextErrorResponse("invalid parameters: " + err.Error()), nil
		}
	}
	res, out, err := t.run(ctx, in)
	if err != nil {
		return fantasy.NewTextErrorResponse(t.name + ": " + err.Error()), nil
	}
	body := mcpResultText(res)
	if res != nil && res.IsError {
		if strings.TrimSpace(body) == "" {
			body = "(empty error result)"
		}
		return fantasy.NewTextErrorResponse(body), nil
	}
	if j, err := json.Marshal(out); err == nil {
		js := string(j)
		switch {
		case js == "{}" || js == "null":
		case strings.TrimSpace(body) == "" || body == js:
			body = js
		default:
			body = body + "\n" + js
		}
	}
	if strings.TrimSpace(body) == "" {
		body = "(empty result)"
	}
	return fantasy.NewTextResponse(truncateMiddle(body)), nil
}

func (t *bridgeAgentTool[In, Out]) ProviderOptions() fantasy.ProviderOptions { return t.opts }
func (t *bridgeAgentTool[In, Out]) SetProviderOptions(opts fantasy.ProviderOptions) {
	t.opts = opts
}

func mcpResultText(res *mcp.CallToolResult) string {
	if res == nil {
		return ""
	}
	var b strings.Builder
	for _, c := range res.Content {
		if tc, ok := c.(*mcp.TextContent); ok {
			b.WriteString(tc.Text)
		}
	}
	return b.String()
}

// agentLinearTools builds the 12 linear_* native twins for one
// session. The ask-built-in workflow tools used to live here too but
// were promoted to the core wire toolset in agent_tools_workflow.go.
// Tool names match what the bridge exposes so prompts and saved
// workflows keep working unchanged.
func agentLinearTools(env *agentToolEnv) []fantasy.AgentTool {
	cwd := func() string { return env.cwd }
	return []fantasy.AgentTool{
		nativeBridgeTool("linear_list_issues", linearListToolDescription,
			func(ctx context.Context, in linearListInput) (*mcp.CallToolResult, linearListOutput, error) {
				return linearListCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_get_issue", linearGetToolDescription,
			func(ctx context.Context, in linearGetInput) (*mcp.CallToolResult, linearGetOutput, error) {
				return linearGetCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_update_issue", linearUpdateToolDescription,
			func(ctx context.Context, in linearUpdateInput) (*mcp.CallToolResult, linearUpdateOutput, error) {
				return linearUpdateCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_create_comment", linearCreateCommentToolDescription,
			func(ctx context.Context, in linearCommentInput) (*mcp.CallToolResult, linearCommentOutput, error) {
				return linearCreateCommentCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_create_issue", linearCreateIssueToolDescription,
			func(ctx context.Context, in linearCreateInput) (*mcp.CallToolResult, linearCreateOutput, error) {
				return linearCreateIssueCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_delete_issue", linearDeleteIssueToolDescription,
			func(ctx context.Context, in linearDeleteInput) (*mcp.CallToolResult, linearDeleteOutput, error) {
				return linearDeleteIssueCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_teams", linearListTeamsToolDescription,
			func(ctx context.Context, in linearListTeamsInput) (*mcp.CallToolResult, linearListTeamsOutput, error) {
				return linearListTeamsCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_users", linearListUsersToolDescription,
			func(ctx context.Context, in linearListUsersInput) (*mcp.CallToolResult, linearListUsersOutput, error) {
				return linearListUsersCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_labels", linearListLabelsToolDescription,
			func(ctx context.Context, in linearListLabelsInput) (*mcp.CallToolResult, linearListLabelsOutput, error) {
				return linearListLabelsCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_states", linearListStatesToolDescription,
			func(ctx context.Context, in linearListStatesInput) (*mcp.CallToolResult, linearListStatesOutput, error) {
				return linearListStatesCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_projects", linearListProjectsToolDescription,
			func(ctx context.Context, in linearListProjectsInput) (*mcp.CallToolResult, linearListProjectsOutput, error) {
				return linearListProjectsCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_cycles", linearListCyclesToolDescription,
			func(ctx context.Context, in linearListCyclesInput) (*mcp.CallToolResult, linearListCyclesOutput, error) {
				return linearListCyclesCore(ctx, cwd(), in)
			}),
	}
}
