package main

import (
	"context"
	"encoding/json"
	"strings"

	"charm.land/fantasy"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// agent_tools_bridge.go gives the in-process agent sessions native
// twins of every loopback-bridge tool (linear_*, workflow_*) so they
// no longer attach the HTTP bridge at all. The bridge handlers and
// these natives share the same cwd-parameterized core functions
// (mcp_linear.go / mcp_workflows.go), so behavior — gating, errors,
// output shapes — is identical on both paths.

// nativeBridgeTool adapts one bridge core to fantasy's AgentTool. The
// input schema is generated by the same jsonschema machinery the MCP
// SDK uses, so the `jsonschema:"..."` field docs the bridge tools were
// written with reach the model unchanged. The returned text is the
// handler's summary line plus the structured output JSON (when the
// two differ), mirroring what an MCP client sees as text + structured
// content.
func nativeBridgeTool[In, Out any](name, description string,
	run func(ctx context.Context, in In) (*mcp.CallToolResult, Out, error),
) fantasy.AgentTool {
	properties := map[string]any{}
	var required []string
	if schema, err := jsonschema.For[In](nil); err == nil {
		if raw, err := json.Marshal(schema); err == nil {
			var m map[string]any
			if json.Unmarshal(raw, &m) == nil {
				if props, ok := m["properties"].(map[string]any); ok {
					properties = props
				}
				if reqs, ok := m["required"].([]any); ok {
					for _, r := range reqs {
						if s, ok := r.(string); ok {
							required = append(required, s)
						}
					}
				}
			}
		}
	} else {
		debugLog("bridge tool %s: schema: %v", name, err)
	}
	return &bridgeAgentTool[In, Out]{
		name:        name,
		description: description,
		properties:  properties,
		required:    required,
		run:         run,
	}
}

type bridgeAgentTool[In, Out any] struct {
	name        string
	description string
	properties  map[string]any
	required    []string
	run         func(ctx context.Context, in In) (*mcp.CallToolResult, Out, error)
	opts        fantasy.ProviderOptions
}

func (t *bridgeAgentTool[In, Out]) Info() fantasy.ToolInfo {
	required := t.required
	if required == nil {
		required = []string{}
	}
	return fantasy.ToolInfo{
		Name:        t.name,
		Description: t.description,
		Parameters:  t.properties,
		Required:    required,
	}
}

func (t *bridgeAgentTool[In, Out]) Run(ctx context.Context, call fantasy.ToolCall) (fantasy.ToolResponse, error) {
	var in In
	if strings.TrimSpace(call.Input) != "" {
		if err := json.Unmarshal([]byte(call.Input), &in); err != nil {
			return fantasy.NewTextErrorResponse("invalid parameters: " + err.Error()), nil
		}
	}
	res, out, err := t.run(ctx, in)
	if err != nil {
		return fantasy.NewTextErrorResponse(t.name + ": " + err.Error()), nil
	}
	body := mcpResultText(res)
	if res != nil && res.IsError {
		if strings.TrimSpace(body) == "" {
			body = "(empty error result)"
		}
		return fantasy.NewTextErrorResponse(body), nil
	}
	if j, err := json.Marshal(out); err == nil {
		js := string(j)
		switch {
		case js == "{}" || js == "null":
		case strings.TrimSpace(body) == "" || body == js:
			body = js
		default:
			body = body + "\n" + js
		}
	}
	if strings.TrimSpace(body) == "" {
		body = "(empty result)"
	}
	return fantasy.NewTextResponse(truncateMiddle(body)), nil
}

func (t *bridgeAgentTool[In, Out]) ProviderOptions() fantasy.ProviderOptions { return t.opts }
func (t *bridgeAgentTool[In, Out]) SetProviderOptions(opts fantasy.ProviderOptions) {
	t.opts = opts
}

func mcpResultText(res *mcp.CallToolResult) string {
	if res == nil {
		return ""
	}
	var b strings.Builder
	for _, c := range res.Content {
		if tc, ok := c.(*mcp.TextContent); ok {
			b.WriteString(tc.Text)
		}
	}
	return b.String()
}

// agentBridgeTools builds the full native tool set for one session:
// the 12 linear_* tools and the 5 workflow CRUD tools plus
// workflow_run. ask_user_question and end_turn already have natives in
// agent_tools_ask.go. Tool names match what the bridge exposes so
// prompts and saved workflows keep working unchanged.
func agentBridgeTools(env *agentToolEnv) []fantasy.AgentTool {
	cwd := func() string { return env.cwd }
	return []fantasy.AgentTool{
		nativeBridgeTool("linear_list_issues", linearListToolDescription,
			func(ctx context.Context, in linearListInput) (*mcp.CallToolResult, linearListOutput, error) {
				return linearListCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_get_issue", linearGetToolDescription,
			func(ctx context.Context, in linearGetInput) (*mcp.CallToolResult, linearGetOutput, error) {
				return linearGetCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_update_issue", linearUpdateToolDescription,
			func(ctx context.Context, in linearUpdateInput) (*mcp.CallToolResult, linearUpdateOutput, error) {
				return linearUpdateCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_create_comment", linearCreateCommentToolDescription,
			func(ctx context.Context, in linearCommentInput) (*mcp.CallToolResult, linearCommentOutput, error) {
				return linearCreateCommentCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_create_issue", linearCreateIssueToolDescription,
			func(ctx context.Context, in linearCreateInput) (*mcp.CallToolResult, linearCreateOutput, error) {
				return linearCreateIssueCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_delete_issue", linearDeleteIssueToolDescription,
			func(ctx context.Context, in linearDeleteInput) (*mcp.CallToolResult, linearDeleteOutput, error) {
				return linearDeleteIssueCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_teams", linearListTeamsToolDescription,
			func(ctx context.Context, in linearListTeamsInput) (*mcp.CallToolResult, linearListTeamsOutput, error) {
				return linearListTeamsCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_users", linearListUsersToolDescription,
			func(ctx context.Context, in linearListUsersInput) (*mcp.CallToolResult, linearListUsersOutput, error) {
				return linearListUsersCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_labels", linearListLabelsToolDescription,
			func(ctx context.Context, in linearListLabelsInput) (*mcp.CallToolResult, linearListLabelsOutput, error) {
				return linearListLabelsCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_states", linearListStatesToolDescription,
			func(ctx context.Context, in linearListStatesInput) (*mcp.CallToolResult, linearListStatesOutput, error) {
				return linearListStatesCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_projects", linearListProjectsToolDescription,
			func(ctx context.Context, in linearListProjectsInput) (*mcp.CallToolResult, linearListProjectsOutput, error) {
				return linearListProjectsCore(ctx, cwd(), in)
			}),
		nativeBridgeTool("linear_list_cycles", linearListCyclesToolDescription,
			func(ctx context.Context, in linearListCyclesInput) (*mcp.CallToolResult, linearListCyclesOutput, error) {
				return linearListCyclesCore(ctx, cwd(), in)
			}),

		nativeBridgeTool("workflow_list", workflowListToolDescription,
			func(_ context.Context, in workflowListInput) (*mcp.CallToolResult, workflowListOutput, error) {
				return workflowListCore(cwd(), in)
			}),
		nativeBridgeTool("workflow_get", workflowGetToolDescription,
			func(_ context.Context, in workflowGetInput) (*mcp.CallToolResult, workflowGetOutput, error) {
				return workflowGetCore(cwd(), in)
			}),
		nativeBridgeTool("workflow_create", workflowCreateToolDescription,
			func(_ context.Context, in workflowCreateInput) (*mcp.CallToolResult, workflowCreateOutput, error) {
				return workflowCreateCore(cwd(), in)
			}),
		nativeBridgeTool("workflow_edit", workflowEditToolDescription,
			func(_ context.Context, in workflowEditInput) (*mcp.CallToolResult, workflowEditOutput, error) {
				return workflowEditCore(cwd(), in)
			}),
		nativeBridgeTool("workflow_delete", workflowDeleteToolDescription,
			func(_ context.Context, in workflowDeleteInput) (*mcp.CallToolResult, workflowDeleteOutput, error) {
				return workflowDeleteCore(cwd(), in)
			}),
		nativeBridgeTool("workflow_run", workflowRunToolDescription,
			func(_ context.Context, in workflowRunInput) (*mcp.CallToolResult, workflowRunOutput, error) {
				return workflowRunCore(cwd(), env.tabID, in)
			}),
	}
}
